
project_id = "tijdikovauumiduljnrm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[functions]
[functions.get-rss-feed]
verify_jwt = false

[functions.analyze-feedback]
verify_jwt = false

[functions.generate-glossary]
verify_jwt = false

[functions.generate-program]
verify_jwt = false

[functions.generate-video-script]
verify_jwt = false

