// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tijdikovauumiduljnrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpamRpa292YXV1bWlkdWxqbnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMTkyMDgsImV4cCI6MjA1Mzg5NTIwOH0.0kEvhLp_MMtANNum6kZbxAw97Tdu_RoniAj22Dsp1rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);